#!/usr/bin/env python3
"""
WA prompt compression profile — re-runnable audit.

Walks mvp_site/prompts/ and emits:
  - top-N file sizes (bytes + lines)
  - duplicate-fragment pairs (files that share 80+-char normalized fingerprints)
  - PROMPT_INCLUDE inventory (each shared/* file's parent refs)
  - orphaned shared/* files (no PROMPT_INCLUDE refs from anywhere)
  - rule vs reference classification for the top-N largest files

Usage:
  python3 scripts/wa_prompt_compression_profile.py [REPO_ROOT] [--top 5] [--window 80]

Default REPO_ROOT is the project root (one above mvp_site/prompts/).
Stdout is a markdown report ready to paste into a PR or /tmp scratch file.

Verified 2026-08-18 against ${HOME}/worldarchitect.ai_rate_25.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from collections import defaultdict
from pathlib import Path


PROMPT_DIR = "mvp_site/prompts"
WINDOW = 80
TOP_N = 5

RULE_PATTERN = re.compile(
    r"(\bMUST\b|\bMANDATORY\b|🚨|\bCRITICAL\b|\bHARD INVARIANT\b|\bREQUIRED\b|🚫|⚠️)"
)
CODE_BLOCK = re.compile(r"^\s*```")
TABLE_ROW = re.compile(r"^\s*\|")


def walk_prompts(repo_root: Path) -> list[Path]:
    p = repo_root / PROMPT_DIR
    if not p.is_dir():
        sys.exit(f"missing {p}")
    return sorted(x for x in p.rglob("*.md") if x.is_file())


def file_sizes(paths: list[Path]) -> list[tuple[int, int, Path]]:
    out = []
    for p in paths:
        text = p.read_text(encoding="utf-8", errors="replace")
        out.append((len(text), len(text.splitlines()), p))
    out.sort(key=lambda t: (-t[0], str(t[2])))
    return out


def duplicate_fragments(
    paths: list[Path], window: int, repo_root: Path
) -> list[tuple[list[str], list[Path]]]:
    fp_to_files: dict[str, set[Path]] = defaultdict(set)
    for p in paths:
        text = p.read_text(encoding="utf-8", errors="replace")
        norm = re.sub(r"\s+", " ", text).strip()
        for i in range(0, len(norm) - window, window):
            fp = norm[i : i + window]
            if len(fp) < window:
                continue
            if fp.count("|") > 30 or fp.count("-") > 60:
                continue
            fp_to_files[fp].add(p)
    groups = [(fp, sorted(files)) for fp, files in fp_to_files.items() if len(files) >= 2]
    by_fileset: dict[tuple, list[str]] = defaultdict(list)
    for fp, files in groups:
        by_fileset[tuple(files)].append(fp)
    ranked = sorted(
        by_fileset.items(),
        key=lambda x: (-len(x[0]), -len(x[1])),
    )

    def is_rooted(t: Path) -> bool:
        rel = t.relative_to(repo_root / PROMPT_DIR)
        return rel.parts[0] not in ("shared", "multiverse", "divine")

    return [
        (fps, files)
        for files, fps in ranked
        if any(is_rooted(f) for f in files)
    ]


def prompt_include_inventory(paths: list[Path]) -> dict[Path, list[Path]]:
    inv: dict[Path, list[Path]] = defaultdict(list)
    for p in paths:
        text = p.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r"\{\{PROMPT_INCLUDE:([^}]+)\}\}", text):
            rel = m.group(1).strip()
            target = (p.parent / rel).resolve()
            if target.is_file():
                inv[target].append(p)
    return inv


def rule_vs_reference(paths: list[Path]) -> list[tuple[Path, int, int, int, int]]:
    out = []
    for p in paths:
        text = p.read_text(encoding="utf-8", errors="replace")
        lines = text.splitlines()
        rule = example = table = 0
        in_code = False
        for line in lines:
            if CODE_BLOCK.match(line):
                in_code = not in_code
                example += 1
                continue
            if in_code:
                example += 1
                continue
            if TABLE_ROW.match(line):
                table += 1
            if RULE_PATTERN.search(line):
                rule += 1
        out.append((p, len(lines), rule, example, table))
    return out


def render_markdown(
    repo_root: Path,
    sizes: list[tuple[int, int, Path]],
    dupes: list[tuple[list[str], list[Path]]],
    inv: dict[Path, list[Path]],
    rule_ref: list[tuple[Path, int, int, int, int]],
    top_n: int,
) -> str:
    out = []
    out.append(f"# WA Prompt Compression Profile — {repo_root}\n")
    out.append(f"Source: `{PROMPT_DIR}/`. Generated by `wa_prompt_compression_profile.py`.\n")
    out.append(f"## Top-{top_n} largest files\n")
    out.append("| bytes | lines | path |")
    out.append("|---|---|---|")
    for size, lines, p in sizes[:top_n]:
        rel = p.relative_to(repo_root)
        out.append(f"| {size} | {lines} | `{rel}` |")
    out.append("")
    out.append(f"Total: {sum(s for s, _, _ in sizes)} bytes across {len(sizes)} files.\n")

    out.append("## Duplicate fragments (>= 80-char normalized fingerprints)\n")
    if not dupes:
        out.append("None detected above the threshold.\n")
    else:
        for fps, files in dupes[:5]:
            out.append(f"### {len(fps)} shared fingerprints across {len(files)} files")
            for f in sorted(files):
                out.append(f"- `{f.relative_to(repo_root)}`")
            if fps:
                out.append(f"\n  sample: `{fps[0]!r}`\n")
            out.append("")

    out.append("## PROMPT_INCLUDE inventory (`shared/*` files)\n")
    shared = sorted(
        p for p in inv
        if any(part in p.parts for part in ("shared", "multiverse", "divine"))
    )
    for p in shared:
        rel = p.relative_to(repo_root)
        parents = inv[p]
        out.append(f"- `{rel}` ← {len(parents)} parent ref(s)")
    all_paths = [p for _, _, p in sizes]
    orphaned = [
        p for p in all_paths
        if "shared" in p.parts and p not in inv
    ]
    if orphaned:
        out.append("\n### Orphaned shared/* files (no PROMPT_INCLUDE refs — verify before deleting)\n")
        for p in orphaned:
            out.append(f"- `{p.relative_to(repo_root)}`")
    out.append("")

    out.append("## Rule vs reference (top-N largest)\n")
    rel_map = {p: data for p, *data in rule_ref}
    out.append("| file | total lines | rule | code/example | table |")
    out.append("|---|---|---|---|---|")
    for size, lines, p in sizes[:top_n]:
        if p in rel_map:
            _, total, rule, ex, tbl = rel_map[p]
            out.append(
                f"| `{p.relative_to(repo_root)}` | {total} | "
                f"{rule} ({100*rule/max(total,1):.0f}%) | "
                f"{ex} ({100*ex/max(total,1):.0f}%) | "
                f"{tbl} ({100*tbl/max(total,1):.0f}%) |"
            )
    out.append("")

    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("repo_root", nargs="?", default=".")
    parser.add_argument("--top", type=int, default=TOP_N)
    parser.add_argument("--window", type=int, default=WINDOW)
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    paths = walk_prompts(repo_root)
    sizes = file_sizes(paths)
    dupes = duplicate_fragments(paths, args.window, repo_root)
    inv = prompt_include_inventory(paths)
    rule_ref = rule_vs_reference([p for _, _, p in sizes[: args.top]])
    print(render_markdown(repo_root, sizes, dupes, inv, rule_ref, args.top))


if __name__ == "__main__":
    main()
