#!/usr/bin/env bash
# test_resolve_review_threads.sh — RED-GREEN tests for lib/resolve_review_threads.sh
#
# Verifies the is_nit_comment filter and the list/resolve dispatch path
# against fake PR fixtures. Network calls are NOT made; the list helper
# is exercised via a mocked gh script on PATH that reads a fixture file.
#
# Run:  bash tests/test_resolve_review_threads.sh

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
LIB="$(cd "$HERE/.." && pwd)/lib/resolve_review_threads.sh"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Sanity: fixture files must exist (generated by `make test-fixtures` or
# committed alongside this test).
for f in "$HERE/fixture_list.json" "$HERE/fixture_dry.json"; do
  if [ ! -f "$f" ]; then
    echo "MISSING: $f" >&2
    echo "Generate via: python3 - > $f (see test script source)" >&2
    exit 1
  fi
  python3 -c "import json; json.load(open('$f'))" || { echo "INVALID JSON: $f" >&2; exit 1; }
done

# --- Test 1: is_nit_comment filter on real-world examples --------------------
echo "TEST 1: is_nit_comment"
IS_SOURCED=1
# shellcheck disable=SC1090
source "$LIB"

assert_nit() {
  local body="$1" expected="$2" desc="$3"
  if is_nit_comment "$body"; then actual="true"; else actual="false"; fi
  if [ "$actual" = "$expected" ]; then
    echo "  ✓ $desc"
  else
    echo "  ✗ $desc (body='$body' got=$actual want=$expected)" >&2
    exit 1
  fi
}

assert_nit "nit: typo on line 3"          "true"  "lowercase nit:"
assert_nit "Nit: rename x to y"            "true"  "Title-case Nit:"
assert_nit "NITPICK: bigger issue"         "true"  "all-caps NITPICK:"
assert_nit "  nit: leading space"          "true"  "leading whitespace"
assert_nit "Real bug: missing return"      "false" "non-nit body"
assert_nit ""                              "false" "empty body"
assert_nit "nitrate: chemistry word"       "false" "nitrate, not nit:"
assert_nit "initialize"                    "false" "innocuous word"

# --- Test 2: dispatch to list/one/main without args gives a usage message ----
echo ""
echo "TEST 2: dispatch surface"
out="$("$LIB" 2>&1 || true)"
if [[ "$out" == *"Usage:"* ]] || [[ "$out" == *"PR_NUMBER"* ]]; then
  echo "  ✓ main with no args prints usage"
else
  echo "  ✗ main with no args did not print usage: $out" >&2
  exit 1
fi

# --- Test 3: list path with mocked gh ---------------------------------------
echo ""
echo "TEST 3: list with mocked gh"

mkdir -p "$TMP/bin"
cat >"$TMP/bin/gh" <<'GH'
#!/usr/bin/env bash
case "$1" in
  repo)
    echo "jleechanorg/jleechanbrain"
    ;;
  api)
    cat "$FIXTURE_PATH"
    ;;
esac
GH
chmod +x "$TMP/bin/gh"

# Force PATH to put mock first, pass owner/repo explicitly to skip auto-detect.
export PATH="$TMP/bin:$PATH"
export FIXTURE_PATH="$HERE/fixture_list.json"
IS_SOURCED=1 source "$LIB"
list_out="$(resolve_review_threads_list 621 jleechanorg jleechanbrain)"

# Expect: PRRT_CODEX_THREAD only. The nit (PRRT_NIT_THREAD) is filtered out.
# The PR author's own thread is filtered. The resolved one is filtered.
expected="PRRT_CODEX_THREAD"
if [ "$list_out" = "$expected" ]; then
  echo "  ✓ list returns only the codex-connector non-nit non-PR-author thread"
else
  echo "  ✗ list filter wrong:" >&2
  echo "    got:      '$list_out'" >&2
  echo "    expected: '$expected'" >&2
  exit 1
fi

# --- Test 4: self-test runs and reports 0 failures --------------------------
echo ""
echo "TEST 4: self-test"
out="$(bash "$LIB" self-test 2>&1)"
if [[ "$out" == *"0 fail"* ]]; then
  echo "  ✓ self-test reports 0 failures: $out"
else
  echo "  ✗ self-test reported failures: $out" >&2
  exit 1
fi

# --- Test 5: --dry-run path doesn't make mutation calls ---------------------
echo ""
echo "TEST 5: --dry-run"

cat >"$TMP/bin/gh" <<'GH'
#!/usr/bin/env bash
case "$1" in
  repo)
    echo "jleechanorg/jleechanbrain"
    ;;
  api)
    if grep -q "resolveReviewThread" <<<"$*"; then
      echo "MUTATION_WAS_CALLED" >&2
      exit 99
    fi
    cat "$FIXTURE_PATH"
    ;;
esac
GH
chmod +x "$TMP/bin/gh"

out="$(PATH="$TMP/bin:$PATH" FIXTURE_PATH="$HERE/fixture_dry.json" bash "$LIB" 621 --dry-run 2>&1)" || true
if [[ "$out" == *"would resolve: PRRT_DRY_THREAD"* ]]; then
  echo "  ✓ --dry-run prints 'would resolve' instead of calling mutation"
else
  echo "  ✗ --dry-run failed. Output: $out" >&2
  exit 1
fi

echo ""
echo "ALL TESTS PASSED"
