#!/usr/bin/env bash
# slack-thread-roadmap-demo.sh
#
# Synthetic demo: render a real LLM-judged roadmap report from 3 hand-crafted
# threads so Jeffrey can see what a populated report looks like without having
# to wait for real dropped threads to accumulate.
#
# This is a one-shot, NOT a cron job. It:
#   1. Builds a 3-thread synthetic bundle (cold, in-progress, already-done)
#   2. Calls the LLM (shared helper lib-llm-judgment.sh) for structured judgment
#   3. Renders a markdown report
#   4. Pushes to jleechanorg/roadmap origin main
set -euo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin${PATH:+:$PATH}"

HERMES_HOME="${HERMES_HOME:-${HOME}/.smartclaw}"
ROADMAP_REPO="${ROADMAP_REPO:-jleechanorg/roadmap}"
ROADMAP_BRANCH="${ROADMAP_BRANCH:-main}"

# Source the shared LLM helper from the first available location. The lib
# bails on missing env. Mirrors the same candidate fallback in
# slack-thread-roadmap-report.sh so both callers resolve the same way.
LIB=""
for candidate in \
  "$HERMES_HOME/scripts/lib-llm-judgment.sh" \
  "$HOME/.smartclaw/scripts/lib-llm-judgment.sh" \
  "$HOME/.smartclaw/scripts/lib-llm-judgment.sh"; do
  if [[ -f "$candidate" ]]; then
    LIB="$candidate"
    break
  fi
done
if [[ -z "$LIB" ]]; then
  echo "lib-llm-judgment.sh not found in any candidate path" >&2
  exit 1
fi
# shellcheck disable=SC1090
source "$LIB"

# ── Synthetic thread bundle ────────────────────────────────────────────────────
# 3 realistic threads spanning the dropped-thread kind spectrum.
read -r -d '' THREADS_BUNDLE <<'BUNDLE' || true
CHANNEL=${SLACK_CHANNEL_ID}
THREAD_TS=1781801320.769139
THREAD_URL=https://jleechanai.slack.com/archives/${SLACK_CHANNEL_ID}/p1781801320769139
KIND=cold
AGE_HOURS=10
REASON="rate-limit PR #7618 should have been merged by now per the thread context"
DIGEST_START
[1781801320.769139] <U09GH5BR3QU> I thought we already had a PR to fix this? Run /ms and search PR history to see what we did
[1781801345.000000] <U0AEZC7RX1Q> Searching PR history for rate-limit work now.
[1781801399.000000] <U0AEZC7RX1Q> Found PR #7618 from 2026-06-16 — it was /green'd but the agent loop timed out before push.
[1781801401.000000] <U0AEZC7RX1Q> PR is in draft state on the branch feature/rate-limit-25-daily. Need 2 more commits to land.
DIGEST_END

---

CHANNEL=C0AH3RY3DK6
THREAD_TS=1781830987.334969
THREAD_URL=https://jleechanai.slack.com/archives/C0AH3RY3DK6/p1781830987334969
KIND=stale-dispatch
AGE_HOURS=23
REASON="ao-worker dispatched 23h ago on /green PR #7659, no progress report posted"
DIGEST_START
[1781830987.334969] <U09GH5BR3QU> lets /green this PR https://github.com/jleechanorg/worldarchitect.ai/pull/7659
[1781831010.000000] <U0AEZC7RX1Q> Spawning AO worker on PR #7659. Will report back here.
[1781831050.000000] <U0AEZC7RX1Q> ao-worker running gates; current: tdd tests passing, 7-green pending.
DIGEST_END

---

CHANNEL=C0AH3RY3DK6
THREAD_TS=1781811586.832649
THREAD_URL=https://jleechanai.slack.com/archives/C0AH3RY3DK6/p1781811586832649
KIND=standalone
AGE_HOURS=5
REASON="code-standards skill update requested, partial-state reply posted"
DIGEST_START
[1781811586.832649] <U09GH5BR3QU> review this prompt and add it as a skill that /code-standards calls and call it durable-user-preference-commit
[1781811600.000000] <U0AEZC7RX1Q> Reading the prompt now. Will add as skill at ~/.claude/skills/durable-user-preference-commit/SKILL.md.
[1781811690.000000] <U0AEZC7RX1Q> Genesis Coder, Prime Mover, [partial-state reply per finish-the-job]: PR https://github.com/jleechanorg/worldarchitect.ai/pull/7718 opened.
[1781812000.000000] <U09GH5BR3QU> approved, ship it
[1781812010.000000] <U0AEZC7RX1Q> PR #7718 merged. Skill live at ~/.claude/skills/durable-user-preference-commit/SKILL.md.
DIGEST_END
BUNDLE

TMP=$(mktemp -d -t roadmap-demo.XXXXXX)
NUM_THREADS=3

echo "→ calling LLM (shared helper) for $NUM_THREADS synthetic threads..."
if ! LLM_JUDGMENT=$(llm_judgment_for_threads "$TMP" "$NUM_THREADS" "$THREADS_BUNDLE" 2>"$TMP/err"); then
  echo "LLM call failed: $(cat "$TMP/err")" >&2
  exit 1
fi
echo "✓ LLM call succeeded ($(echo -n "$LLM_JUDGMENT" | wc -c | tr -d ' ') bytes)"
echo ""

# ── Render report ─────────────────────────────────────────────────────────────
NOW_LOCAL=$(date '+%Y-%m-%d %H:%M:%S %Z')
REPORT_DATE=$(date '+%Y-%m-%d')
REPORT_TIME=$(date '+%H%M')
REPORT_FILE="${REPORT_DATE}-${REPORT_TIME}-slack-thread-roadmap-demo.md"

cat > "$TMP/$REPORT_FILE" <<EOF
# Slack thread roadmap — $REPORT_DATE $REPORT_TIME (DEMO)

*Generated by* \`ai.smartclaw.schedule.slack-thread-roadmap-demo\` (one-shot synthetic)
*Source*: 3 hand-curated threads spanning the dropped-thread kind spectrum
*Generated at*: $NOW_LOCAL
*Lookback*: last 48h
*Channels*: \`C0AH3RY3DK6 ${SLACK_CHANNEL_ID}\`
*Actionable threads*: $NUM_THREADS (synthetic)

## Executive summary

$LLM_JUDGMENT

---

*Cron (production)*: \`ai.smartclaw.schedule.slack-thread-roadmap-report\` — every 4h 08/12/16/20 local + 00:00 midnight sweep
*Log*: \`~/.smartclaw/logs/slack-thread-roadmap-report.log\`
EOF

echo "→ report rendered: $REPORT_FILE"
head -10 "$TMP/$REPORT_FILE"
echo "..."

# ── Commit + push to roadmap repo ─────────────────────────────────────────────
WORKTREE_DIR="$HOME/.worktrees/roadmap-demo-$$"
echo "→ creating worktree at $WORKTREE_DIR"
git -C "$HERMES_HOME" fetch origin --quiet 2>/dev/null || true
gh repo clone "$ROADMAP_REPO" "$WORKTREE_DIR" -- --branch "$ROADMAP_BRANCH" --quiet 2>/dev/null || {
  # Fall back: clone with full URL
  git clone "https://github.com/$ROADMAP_REPO.git" "$WORKTREE_DIR" --branch "$ROADMAP_BRANCH" --quiet
}
git -C "$WORKTREE_DIR" config user.email "jleechan@gmail.com"
git -C "$WORKTREE_DIR" config user.name "jleechan"
git -C "$WORKTREE_DIR" checkout "$ROADMAP_BRANCH" --quiet
git -C "$WORKTREE_DIR" pull --rebase --quiet origin "$ROADMAP_BRANCH" 2>/dev/null || true
cp "$TMP/$REPORT_FILE" "$WORKTREE_DIR/$REPORT_FILE"
git -C "$WORKTREE_DIR" add "$REPORT_FILE"
git -C "$WORKTREE_DIR" commit -m "chore(roadmap): slack thread action plan — $REPORT_DATE $REPORT_TIME (DEMO)" --quiet
git -C "$WORKTREE_DIR" push origin "$ROADMAP_BRANCH" --quiet
COMMIT_SHA=$(git -C "$WORKTREE_DIR" rev-parse HEAD)
echo "✓ pushed: https://github.com/$ROADMAP_REPO/commit/$COMMIT_SHA"
echo "✓ report URL: https://github.com/$ROADMAP_REPO/blob/$ROADMAP_BRANCH/$REPORT_FILE"

# Cleanup worktree
git -C "$WORKTREE_DIR" worktree remove --force 2>/dev/null || rm -rf "$WORKTREE_DIR"
