#!/usr/bin/env bash
# staging-gateway.sh — Start/stop/status for Hermes staging gateway
# Production runs on 18789; staging uses ~/.smartclaw + config.staging.yaml on a separate port.
# This script delegates to launchd (ai.smartclaw.staging) for reliable long-running operation.
set -euo pipefail

STAGING_PORT="${HERMES_STAGING_PORT:-18810}"
HERMES_DIR="${HOME}/.smartclaw"
STAGING_CONFIG="${HERMES_DIR}/config.staging.yaml"
STAGING_LABEL="ai.smartclaw.staging"
NODE_BIN="${HERMES_NODE_BIN:-$HOME/.nvm/versions/node/v22.22.0/bin/node}"
HERMES_DIST_JS="${HERMES_DIST_JS:-${HOMEBREW_PREFIX:-/opt/homebrew}/lib/node_modules/hermes/dist/index.js}"

usage() {
    echo "Usage: $0 {start|stop|status|restart}"
    echo ""
    echo "Manages the Hermes staging gateway on port ${STAGING_PORT}."
    echo "Delegates to launchd label '${STAGING_LABEL}' for reliability."
    echo "Production gateway runs on port 18789."
    exit 1
}

# Guard: staging config must exist
ensure_staging_config() {
    if [[ ! -f "$STAGING_CONFIG" ]]; then
        echo "ERROR: Staging config not found at $STAGING_CONFIG"
        echo "Create it by copying production config:"
        echo "  cp ~/.smartclaw/config.yaml ~/.smartclaw/config.staging.yaml"
        echo "  Then modify port to ${STAGING_PORT} and Slack routing."
        exit 1
    fi
}

start_gateway() {
    ensure_staging_config
    mkdir -p "${HERMES_DIR}/logs"

    local state
    state=$(launchctl print gui/$(id -u)/${STAGING_LABEL} 2>/dev/null | grep "state = " | awk '{print $NF}' || echo "not loaded")
    if [[ "$state" == "running" ]]; then
        echo "Staging gateway already running (launchd: ${STAGING_LABEL}, port: ${STAGING_PORT})"
        return 0
    fi

    # Install + load the plist if not already
    if [[ ! -f "${HERMES_DIR}/ai.smartclaw.staging.plist" ]]; then
        echo "Installing launchd plist..."
        install -m 644 /dev/null "${HERMES_DIR}/ai.smartclaw.staging.plist"
        cat > "${HERMES_DIR}/ai.smartclaw.staging.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>ai.smartclaw.staging</string>
	<key>Comment</key>
	<string>Hermes staging gateway (generated by staging-gateway.sh — no hardcoded user paths)</string>
	<key>EnvironmentVariables</key>
	<dict>
		<key>HOME</key>
		<string>${HOME}</string>
		<key>PATH</key>
		<string>${HOMEBREW_PREFIX:-/opt/homebrew}/bin:${HOME}/.nvm/versions/node/v22.22.0/bin:/usr/local/bin:/usr/bin:/bin</string>
		<key>HERMES_STATE_DIR</key>
		<string>${HERMES_DIR}</string>
		<key>HERMES_CONFIG_PATH</key>
		<string>${STAGING_CONFIG}</string>
		<key>HERMES_GATEWAY_PORT</key>
		<string>${STAGING_PORT}</string>
		<key>HERMES_PROFILE</key>
		<string>staging</string>
		<key>HERMES_RAW_STREAM</key>
		<string>1</string>
		<key>HERMES_RAW_STREAM_PATH</key>
		<string>/tmp/hermes/staging-raw-stream.jsonl</string>
	</dict>
	<key>KeepAlive</key>
	<true/>
	<key>ProgramArguments</key>
	<array>
		<string>${NODE_BIN}</string>
		<string>${HERMES_DIST_JS}</string>
		<string>gateway</string>
		<string>--port</string>
		<string>${STAGING_PORT}</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardErrorPath</key>
	<string>${HERMES_DIR}/logs/staging-gateway.err.log</string>
	<key>StandardOutPath</key>
	<string>${HERMES_DIR}/logs/staging-gateway.log</string>
</dict>
</plist>
PLIST
    fi

    launchctl bootout gui/$(id -u)/${STAGING_LABEL} 2>/dev/null || true
    launchctl bootstrap gui/$(id -u) "${HERMES_DIR}/ai.smartclaw.staging.plist" 2>&1

    # Wait for health (max 20s)
    echo "Starting staging gateway..."
    local attempts=0
    while [[ $attempts -lt 20 ]]; do
        sleep 1
        attempts=$((attempts + 1))
        if curl -sf "http://127.0.0.1:${STAGING_PORT}/health" >/dev/null 2>&1; then
            echo "Staging gateway started (port: ${STAGING_PORT})"
            return 0
        fi
    done
    echo "WARNING: Gateway started but health endpoint not responding after 20s."
    echo "Check logs: tail -20 ${HERMES_DIR}/logs/staging-gateway.log"
}

stop_gateway() {
    launchctl bootout gui/$(id -u)/${STAGING_LABEL} 2>&1 || true
    echo "Staging gateway stopped"
}

status_gateway() {
    echo "=== Staging Gateway Status ==="
    echo "Port: $STAGING_PORT"
    echo "Config: $STAGING_CONFIG"

    local state pid
    state=$(launchctl print gui/$(id -u)/${STAGING_LABEL} 2>/dev/null | grep "state = " | awk '{print $NF}' || echo "not loaded")
    pid=$(launchctl print gui/$(id -u)/${STAGING_LABEL} 2>/dev/null | grep "pid = " | awk '{print $NF}' || echo "none")

    echo "Launchd: ${state} (pid: ${pid})"

    if lsof -i ":${STAGING_PORT}" 2>/dev/null | grep -q LISTEN; then
        echo "Port: LISTENING"
    else
        echo "Port: NOT LISTENING"
    fi

    if curl -sf --max-time 3 "http://127.0.0.1:${STAGING_PORT}/health" >/dev/null 2>&1; then
        echo "Health: OK"
    else
        echo "Health: UNREACHABLE"
    fi
}

case "${1:-}" in
    start)   start_gateway ;;
    stop)    stop_gateway ;;
    status)  status_gateway ;;
    restart) stop_gateway; sleep 2; start_gateway ;;
    *)       usage ;;
esac
